version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: circle_testing
          - DB_DATABASE: test_sample01
          - DB_USERNAME: root
 
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: test_sample01
 
    steps:
      - checkout
      
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql
 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "kacoichi/composer.json" }}
            - v1-dependencies-
 
      - run: composer install -n --prefer-dist --working-dir=./kacoichi/
 
      - save_cache:
          key: v1-dependencies-{{ checksum "kacoichi/composer.json" }}
          paths:
            - ./vendor
 
      - run: echo "APP_KEY=" > .env.testing
      - run: php ./kacoichi/artisan key:generate --env=testing
      
      - run: docker-compose run app php ./kacoichi/artisan migrate --env=testing
      - run: docker-compose run app php ./kacoichi/artisan db:seed --env=testing
      
      - run: php ./kacoichi/vendor/bin/phpunit --configuration=./kacoichi/phpunit.xml
